# This is a basic workflow to help you get started with Actions

name: msm-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Image Build
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm7150
          - sweet
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Source List
        run: |
          sudo curl -s https://gist.githubusercontent.com/hakerdefo/9c99e140f543b5089e32176fe8721f5f/raw/7ac6ccf882bb0d39297962f0baedce5721c9be65/sources.list > sources.list
          sudo mv -v sources.list /etc/apt/sources.list

      - name: Wine inataller
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources

      - name: Install requires packages
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext
          # sudo apt-get -y install --install-recommends winehq-stable
          sudo apt-get -y install ocl-icd-libopencl1:i386
          sudo apt-get -y install --install-recommends winehq-devel wine-devel wine-devel-amd64

      - name: Build device ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          name: ${{ matrix.device }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.img
